led:
	gcc -o led_blink led_blink.c -lwiringPi -lwiringPiDev -lm -lpthread -lrt -lcrypt

all:
    gcc -o wpi_exam_serial_loopback wpi_exam_serial_loopback.c -lwiringPi -lwiringPiDev -lm -lpthread -lrt -lcrypt
	
